L2MCASTD = l2mcastd.deb
$(L2MCASTD)_SRC_PATH = $(SRC_PATH)/l2mcastd
SONIC_MAKE_DEBS += $(L2MCASTD)

DOCKER_L2MC_STEM = docker-l2mc
DOCKER_L2MC = $(DOCKER_L2MC_STEM).gz
DOCKER_L2MC_DBG = $(DOCKER_L2MC_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_L2MC)_PATH = $(DOCKERS_PATH)/$(DOCKER_L2MC_STEM)
$(DOCKER_L2MC)_CONTAINER_NAME = l2mc
$(DOCKER_L2MC)_VERSION = 1.0.0
$(DOCKER_L2MC)_PACKAGE_NAME = l2mc

$(DOCKER_L2MC)_DEPENDS += $(L2MCASTD)
$(DOCKER_L2MC)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_L2MC)_RUN_OPT += -t --cap-add=NET_ADMIN --cap-add=SYS_ADMIN
$(DOCKER_L2MC)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro

$(DOCKER_L2MC)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_L2MC)_DBG_DEPENDS += $(L2MCASTD)
$(DOCKER_L2MC)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

ifeq ($(INCLUDE_L2MC),y)
SONIC_DOCKER_IMAGES += $(DOCKER_L2MC)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_L2MC)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_L2MC_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_L2MC_DBG)
sonic-vs.img.gz_DOCKERS += $(DOCKER_L2MC)
sonic-vs.bin_DOCKERS += $(DOCKER_L2MC)
endif